export interface Assignment {
    id: number
    position: number
    description: any
    points_possible: number
    grading_type: string
    created_at: string
    updated_at: string
    due_at: any
    final_grader_id: any
    grader_count: number
    graders_anonymous_to_graders: boolean
    grader_comments_visible_to_graders: boolean
    grader_names_visible_to_final_grader: boolean
    lock_at: any
    unlock_at: any
    assignment_group_id: number
    peer_reviews: boolean
    anonymous_peer_reviews: boolean
    automatic_peer_reviews: boolean
    intra_group_peer_reviews: boolean
    post_to_sis: boolean
    grade_group_students_individually: boolean
    group_category_id: any
    grading_standard_id: any
    moderated_grading: boolean
    hide_in_gradebook: boolean
    omit_from_final_grade: boolean
    suppress_assignment: boolean
    anonymous_instructor_annotations: boolean
    anonymous_grading: boolean
    allowed_attempts: number
    annotatable_attachment_id: any
    secure_params: string
    lti_context_id: string
    course_id: number
    name: string
    submission_types: string[]
    has_submitted_submissions: boolean
    due_date_required: boolean
    max_name_length: number
    in_closed_grading_period: boolean
    graded_submissions_exist: boolean
    is_quiz_assignment: boolean
    can_duplicate: boolean
    original_course_id: any
    original_assignment_id: any
    original_lti_resource_link_id: any
    original_assignment_name: any
    original_quiz_id: any
    workflow_state: string
    important_dates: boolean
    muted: boolean
    html_url: string
    published: boolean
    only_visible_to_overrides: boolean
    visible_to_everyone: boolean
    locked_for_user: boolean
    submissions_download_url: string
    post_manually: boolean
    anonymize_students: boolean
    new_quizzes_anonymous_participants: boolean
    require_lockdown_browser: boolean
    restrict_quantitative_data: boolean
}